name: Deploy Website
on:
  push:
    branches:
      - master
jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-east-1
      - name: Install dependencies
        run: bun install
      - name: Build website
        run: bun build
      - name: Deploy static website to S3 bucket
        run: aws s3 sync ./dist s3://rafaaudibert-website --delete
      - name: Invalidate Cloudfront Cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
